### ISSUE TITLE
Ascii art 

### ISSUE THREAD

**Issue by RyanLru** [UnExtraterrestres/jean-le-baptiste#6]
Afficher un ascii art : 

# Affiche un ascii art
# Colorie le texte en jaune clair
echo -e "\e[93m"
cat << "EOF"
      |V|
   .::| |::.
  ::__| |__::
 >____   ____<
  ::  | |  ::
   '::| |::'
      | |
      | |
      |A|

EOF
# Remet la couleur du texte à la normale
echo -e "\e[0m"

# Afficher le passage
echo "Voici le passage quotidien de la Sainte Ecriture : "
echo "$PASSAGE"

**Comment by UnExtraterrestres** [comment]
ajouté chef
